Continent.delete_all
connection.execute("ALTER TABLE continents AUTO_INCREMENT = 1")
Continent.create(:iso => 'AF', :name => 'Africa')
Continent.create(:iso => 'AS', :name => 'Asia')
Continent.create(:iso => 'EU', :name => 'Europe')
Continent.create(:iso => 'NA', :name => 'North America')
Continent.create(:iso => 'SA', :name => 'South America')
Continent.create(:iso => 'OC', :name => 'Oceania')
Continent.create(:iso => 'AN', :name => 'Antarctica')

Country.delete_all
connection.execute("ALTER TABLE countries AUTO_INCREMENT = 1")
Country.create(:iso => 'AF', :continent => Continent.find(2), "Afghanistan")
Country.create(:iso => 'AX', :continent => Continent.find(3), "Åland Islands")
Country.create(:iso => 'AL', :continent => Continent.find(3), "Albania")
Country.create(:iso => 'DZ', :continent => Continent.find(1), "Algeria")
Country.create(:iso => 'AS', :continent => Continent.find(6), "American Samoa")
Country.create(:iso => 'AD', :continent => Continent.find(3), "Andorra")
Country.create(:iso => 'AO', :continent => Continent.find(1), "Angola")
Country.create(:iso => 'AI', :continent => Continent.find(4), "Anguilla")
Country.create(:iso => 'AQ', :continent => Continent.find(7), "Antarctica")
Country.create(:iso => 'AG', :continent => Continent.find(4), "Antigua and Barbuda")
Country.create(:iso => 'AR', :continent => Continent.find(5), "Argentina")
Country.create(:iso => 'AM', :continent => Continent.find(2), "Armenia")
Country.create(:iso => 'AW', :continent => Continent.find(4), "Aruba")
Country.create(:iso => 'AU', :continent => Continent.find(6), "Australia")
Country.create(:iso => 'AT', :continent => Continent.find(3), "Austria")
Country.create(:iso => 'AZ', :continent => Continent.find(2), "Azerbaijan")
Country.create(:iso => 'BS', :continent => Continent.find(4), "Bahamas")
Country.create(:iso => 'BH', :continent => Continent.find(2), "Bahrain")
Country.create(:iso => 'BD', :continent => Continent.find(2), "Bangladesh")
Country.create(:iso => 'BB', :continent => Continent.find(4), "Barbados")
Country.create(:iso => 'BY', :continent => Continent.find(3), "Belarus")
Country.create(:iso => 'BE', :continent => Continent.find(3), "Belgium")
Country.create(:iso => 'BZ', :continent => Continent.find(4), "Belize")
Country.create(:iso => 'BJ', :continent => Continent.find(1), "Benin")
Country.create(:iso => 'BM', :continent => Continent.find(4), "Bermuda")
Country.create(:iso => 'BT', :continent => Continent.find(2), "Bhutan")
Country.create(:iso => 'BO', :continent => Continent.find(5), "Bolivia")
Country.create(:iso => 'BQ', :continent => Continent.find(4), "Bonaire, Sint Eustatius and Saba")
Country.create(:iso => 'BA', :continent => Continent.find(3), "Bosnia and Herzegovina")
Country.create(:iso => 'BW', :continent => Continent.find(1), "Botswana")
Country.create(:iso => 'BV', :continent => Continent.find(7), "Bouvet Island (Bouvetoya)")
Country.create(:iso => 'BR', :continent => Continent.find(5), "Brazil")
Country.create(:iso => 'IO', :continent => Continent.find(2), "British Indian Ocean Territory (Chagos Archipelago)")
Country.create(:iso => 'VG', :continent => Continent.find(4), "British Virgin Islands")
Country.create(:iso => 'BN', :continent => Continent.find(2), "Brunei Darussalam")
Country.create(:iso => 'BG', :continent => Continent.find(3), "Bulgaria")
Country.create(:iso => 'BF', :continent => Continent.find(1), "Burkina Faso")
Country.create(:iso => 'BI', :continent => Continent.find(1), "Burundi")
Country.create(:iso => 'KH', :continent => Continent.find(2), "Cambodia")
Country.create(:iso => 'CM', :continent => Continent.find(1), "Cameroon")
Country.create(:iso => 'CA', :continent => Continent.find(4), "Canada")
Country.create(:iso => 'CV', :continent => Continent.find(1), "Cape Verde")
Country.create(:iso => 'KY', :continent => Continent.find(4), "Cayman Islands")
Country.create(:iso => 'CF', :continent => Continent.find(1), "Central African Republic")
Country.create(:iso => 'TD', :continent => Continent.find(1), "Chad")
Country.create(:iso => 'CL', :continent => Continent.find(5), "Chile")
Country.create(:iso => 'CN', :continent => Continent.find(2), "China")
Country.create(:iso => 'CX', :continent => Continent.find(2), "Christmas Island")
Country.create(:iso => 'CC', :continent => Continent.find(2), "Cocos (Keeling) Islands")
Country.create(:iso => 'CO', :continent => Continent.find(5), "Colombia")
Country.create(:iso => 'KM', :continent => Continent.find(1), "Comoros")
Country.create(:iso => 'CD', :continent => Continent.find(1), "Congo")
Country.create(:iso => 'CG', :continent => Continent.find(1), "Congo")
Country.create(:iso => 'CK', :continent => Continent.find(6), "Cook Islands")
Country.create(:iso => 'CR', :continent => Continent.find(4), "Costa Rica")
Country.create(:iso => 'CI', :continent => Continent.find(1), "Cote d'Ivoire")
Country.create(:iso => 'HR', :continent => Continent.find(3), "Croatia")
Country.create(:iso => 'CU', :continent => Continent.find(4), "Cuba")
Country.create(:iso => 'CW', :continent => Continent.find(4), "Curaçao")
Country.create(:iso => 'CY', :continent => Continent.find(2), "Cyprus")
Country.create(:iso => 'CZ', :continent => Continent.find(3), "Czech Republic")
Country.create(:iso => 'DK', :continent => Continent.find(3), "Denmark")
Country.create(:iso => 'DJ', :continent => Continent.find(1), "Djibouti")
Country.create(:iso => 'DM', :continent => Continent.find(4), "Dominica")
Country.create(:iso => 'DO', :continent => Continent.find(4), "Dominican Republic")
Country.create(:iso => 'EC', :continent => Continent.find(5), "Ecuador")
Country.create(:iso => 'EG', :continent => Continent.find(1), "Egypt")
Country.create(:iso => 'SV', :continent => Continent.find(4), "El Salvador")
Country.create(:iso => 'GQ', :continent => Continent.find(1), "Equatorial Guinea")
Country.create(:iso => 'ER', :continent => Continent.find(1), "Eritrea")
Country.create(:iso => 'EE', :continent => Continent.find(3), "Estonia")
Country.create(:iso => 'ET', :continent => Continent.find(1), "Ethiopia")
Country.create(:iso => 'FO', :continent => Continent.find(3), "Faroe Islands")
Country.create(:iso => 'FK', :continent => Continent.find(5), "Falkland Islands (Malvinas)")
Country.create(:iso => 'FJ', :continent => Continent.find(6), "Fiji")
Country.create(:iso => 'FI', :continent => Continent.find(3), "Finland")
Country.create(:iso => 'FR', :continent => Continent.find(3), "France")
Country.create(:iso => 'GF', :continent => Continent.find(5), "French Guiana")
Country.create(:iso => 'PF', :continent => Continent.find(6), "French Polynesia")
Country.create(:iso => 'TF', :continent => Continent.find(7), "French Southern Territories")
Country.create(:iso => 'GA', :continent => Continent.find(1), "Gabon")
Country.create(:iso => 'GM', :continent => Continent.find(1), "Gambia")
Country.create(:iso => 'GE', :continent => Continent.find(2), "Georgia")
Country.create(:iso => 'DE', :continent => Continent.find(3), "Germany")
Country.create(:iso => 'GH', :continent => Continent.find(1), "Ghana")
Country.create(:iso => 'GI', :continent => Continent.find(3), "Gibraltar")
Country.create(:iso => 'GR', :continent => Continent.find(3), "Greece")
Country.create(:iso => 'GL', :continent => Continent.find(4), "Greenland")
Country.create(:iso => 'GD', :continent => Continent.find(4), "Grenada")
Country.create(:iso => 'GP', :continent => Continent.find(4), "Guadeloupe")
Country.create(:iso => 'GU', :continent => Continent.find(6), "Guam")
Country.create(:iso => 'GT', :continent => Continent.find(4), "Guatemala")
Country.create(:iso => 'GG', :continent => Continent.find(3), "Guernsey")
Country.create(:iso => 'GN', :continent => Continent.find(1), "Guinea")
Country.create(:iso => 'GW', :continent => Continent.find(1), "Guinea-Bissau")
Country.create(:iso => 'GY', :continent => Continent.find(5), "Guyana")
Country.create(:iso => 'HT', :continent => Continent.find(4), "Haiti")
Country.create(:iso => 'HM', :continent => Continent.find(7), "Heard Island and McDonald Islands")
Country.create(:iso => 'VA', :continent => Continent.find(3), "Holy See (Vatican City State)")
Country.create(:iso => 'HN', :continent => Continent.find(4), "Honduras")
Country.create(:iso => 'HK', :continent => Continent.find(2), "Hong Kong")
Country.create(:iso => 'HU', :continent => Continent.find(3), "Hungary")
Country.create(:iso => 'IS', :continent => Continent.find(3), "Iceland")
Country.create(:iso => 'IN', :continent => Continent.find(2), "India")
Country.create(:iso => 'ID', :continent => Continent.find(2), "Indonesia")
Country.create(:iso => 'IR', :continent => Continent.find(2), "Iran")
Country.create(:iso => 'IQ', :continent => Continent.find(2), "Iraq")
Country.create(:iso => 'IE', :continent => Continent.find(3), "Ireland")
Country.create(:iso => 'IM', :continent => Continent.find(3), "Isle of Man")
Country.create(:iso => 'IL', :continent => Continent.find(2), "Israel")
Country.create(:iso => 'IT', :continent => Continent.find(3), "Italy")
Country.create(:iso => 'JM', :continent => Continent.find(4), "Jamaica")
Country.create(:iso => 'JP', :continent => Continent.find(2), "Japan")
Country.create(:iso => 'JE', :continent => Continent.find(3), "Jersey")
Country.create(:iso => 'JO', :continent => Continent.find(2), "Jordan")
Country.create(:iso => 'KZ', :continent => Continent.find(2), "Kazakhstan")
Country.create(:iso => 'KE', :continent => Continent.find(1), "Kenya")
Country.create(:iso => 'KI', :continent => Continent.find(6), "Kiribati")
Country.create(:iso => 'KP', :continent => Continent.find(2), "Democratic People's Republic of Korea")
Country.create(:iso => 'KR', :continent => Continent.find(2), "Republic of Korea")
Country.create(:iso => 'KW', :continent => Continent.find(2), "Kuwait")
Country.create(:iso => 'KG', :continent => Continent.find(2), "Kyrgyz Republic")
Country.create(:iso => 'LA', :continent => Continent.find(2), "Lao People's Democratic Republic")
Country.create(:iso => 'LV', :continent => Continent.find(3), "Latvia")
Country.create(:iso => 'LB', :continent => Continent.find(2), "Lebanon")
Country.create(:iso => 'LS', :continent => Continent.find(1), "Lesotho")
Country.create(:iso => 'LR', :continent => Continent.find(1), "Liberia")
Country.create(:iso => 'LY', :continent => Continent.find(1), "Libya")
Country.create(:iso => 'LI', :continent => Continent.find(3), "Liechtenstein")
Country.create(:iso => 'LT', :continent => Continent.find(3), "Lithuania")
Country.create(:iso => 'LU', :continent => Continent.find(3), "Luxembourg")
Country.create(:iso => 'MO', :continent => Continent.find(2), "Macao")
Country.create(:iso => 'MK', :continent => Continent.find(3), "Macedonia")
Country.create(:iso => 'MG', :continent => Continent.find(1), "Madagascar")
Country.create(:iso => 'MW', :continent => Continent.find(1), "Malawi")
Country.create(:iso => 'MY', :continent => Continent.find(2), "Malaysia")
Country.create(:iso => 'MV', :continent => Continent.find(2), "Maldives")
Country.create(:iso => 'ML', :continent => Continent.find(1), "Mali")
Country.create(:iso => 'MT', :continent => Continent.find(3), "Malta")
Country.create(:iso => 'MH', :continent => Continent.find(6), "Marshall Islands")
Country.create(:iso => 'MQ', :continent => Continent.find(4), "Martinique")
Country.create(:iso => 'MR', :continent => Continent.find(1), "Mauritania")
Country.create(:iso => 'MU', :continent => Continent.find(1), "Mauritius")
Country.create(:iso => 'YT', :continent => Continent.find(1), "Mayotte")
Country.create(:iso => 'MX', :continent => Continent.find(4), "Mexico")
Country.create(:iso => 'FM', :continent => Continent.find(6), "Micronesia")
Country.create(:iso => 'MD', :continent => Continent.find(3), "Moldova")
Country.create(:iso => 'MC', :continent => Continent.find(3), "Monaco")
Country.create(:iso => 'MN', :continent => Continent.find(2), "Mongolia")
Country.create(:iso => 'ME', :continent => Continent.find(3), "Montenegro")
Country.create(:iso => 'MS', :continent => Continent.find(4), "Montserrat")
Country.create(:iso => 'MA', :continent => Continent.find(1), "Morocco")
Country.create(:iso => 'MZ', :continent => Continent.find(1), "Mozambique")
Country.create(:iso => 'MM', :continent => Continent.find(2), "Myanmar")
Country.create(:iso => 'NA', :continent => Continent.find(1), "Namibia")
Country.create(:iso => 'NR', :continent => Continent.find(6), "Nauru")
Country.create(:iso => 'NP', :continent => Continent.find(2), "Nepal")
Country.create(:iso => 'NL', :continent => Continent.find(3), "Netherlands")
Country.create(:iso => 'NC', :continent => Continent.find(6), "New Caledonia")
Country.create(:iso => 'NZ', :continent => Continent.find(6), "New Zealand")
Country.create(:iso => 'NI', :continent => Continent.find(4), "Nicaragua")
Country.create(:iso => 'NE', :continent => Continent.find(1), "Niger")
Country.create(:iso => 'NG', :continent => Continent.find(1), "Nigeria")
Country.create(:iso => 'NU', :continent => Continent.find(6), "Niue")
Country.create(:iso => 'NF', :continent => Continent.find(6), "Norfolk Island")
Country.create(:iso => 'MP', :continent => Continent.find(6), "Northern Mariana Islands")
Country.create(:iso => 'NO', :continent => Continent.find(3), "Norway")
Country.create(:iso => 'OM', :continent => Continent.find(2), "Oman")
Country.create(:iso => 'PK', :continent => Continent.find(2), "Pakistan")
Country.create(:iso => 'PW', :continent => Continent.find(6), "Palau")
Country.create(:iso => 'PS', :continent => Continent.find(2), "Palestinian Territory")
Country.create(:iso => 'PA', :continent => Continent.find(4), "Panama")
Country.create(:iso => 'PG', :continent => Continent.find(6), "Papua New Guinea")
Country.create(:iso => 'PY', :continent => Continent.find(5), "Paraguay")
Country.create(:iso => 'PE', :continent => Continent.find(5), "Peru")
Country.create(:iso => 'PH', :continent => Continent.find(2), "Philippines")
Country.create(:iso => 'PN', :continent => Continent.find(6), "Pitcairn Islands")
Country.create(:iso => 'PL', :continent => Continent.find(3), "Poland")
Country.create(:iso => 'PT', :continent => Continent.find(3), "Portugal")
Country.create(:iso => 'PR', :continent => Continent.find(4), "Puerto Rico")
Country.create(:iso => 'QA', :continent => Continent.find(2), "Qatar")
Country.create(:iso => 'RE', :continent => Continent.find(1), "Réunion")
Country.create(:iso => 'RO', :continent => Continent.find(3), "Romania")
Country.create(:iso => 'RU', :continent => Continent.find(3), "Russian Federation")
Country.create(:iso => 'RW', :continent => Continent.find(1), "Rwanda")
Country.create(:iso => 'BL', :continent => Continent.find(4), "Saint Barthélemy")
Country.create(:iso => 'SH', :continent => Continent.find(1), "Saint Helena, Ascension and Tristan da Cunha")
Country.create(:iso => 'KN', :continent => Continent.find(4), "Saint Kitts and Nevis")
Country.create(:iso => 'LC', :continent => Continent.find(4), "Saint Lucia")
Country.create(:iso => 'MF', :continent => Continent.find(4), "Saint Martin")
Country.create(:iso => 'PM', :continent => Continent.find(4), "Saint Pierre and Miquelon")
Country.create(:iso => 'VC', :continent => Continent.find(4), "Saint Vincent and the Grenadines")
Country.create(:iso => 'WS', :continent => Continent.find(6), "Samoa")
Country.create(:iso => 'SM', :continent => Continent.find(3), "San Marino")
Country.create(:iso => 'ST', :continent => Continent.find(1), "Sao Tome and Principe")
Country.create(:iso => 'SA', :continent => Continent.find(2), "Saudi Arabia")
Country.create(:iso => 'SN', :continent => Continent.find(1), "Senegal")
Country.create(:iso => 'RS', :continent => Continent.find(3), "Serbia")
Country.create(:iso => 'SC', :continent => Continent.find(1), "Seychelles")
Country.create(:iso => 'SL', :continent => Continent.find(1), "Sierra Leone")
Country.create(:iso => 'SG', :continent => Continent.find(2), "Singapore")
Country.create(:iso => 'SX', :continent => Continent.find(4), "Sint Maarten (Dutch part)")
Country.create(:iso => 'SK', :continent => Continent.find(3), "Slovakia (Slovak Republic)")
Country.create(:iso => 'SI', :continent => Continent.find(3), "Slovenia")
Country.create(:iso => 'SB', :continent => Continent.find(6), "Solomon Islands")
Country.create(:iso => 'SO', :continent => Continent.find(1), "Somalia")
Country.create(:iso => 'ZA', :continent => Continent.find(1), "South Africa")
Country.create(:iso => 'GS', :continent => Continent.find(7), "South Georgia and the South Sandwich Islands")
Country.create(:iso => 'SS', :continent => Continent.find(1), "South Sudan")
Country.create(:iso => 'ES', :continent => Continent.find(3), "Spain")
Country.create(:iso => 'LK', :continent => Continent.find(2), "Sri Lanka")
Country.create(:iso => 'SD', :continent => Continent.find(1), "Sudan")
Country.create(:iso => 'SR', :continent => Continent.find(5), "Suriname")
Country.create(:iso => 'SJ', :continent => Continent.find(3), "Svalbard & Jan Mayen Islands")
Country.create(:iso => 'SZ', :continent => Continent.find(1), "Swaziland")
Country.create(:iso => 'SE', :continent => Continent.find(3), "Sweden")
Country.create(:iso => 'CH', :continent => Continent.find(3), "Switzerland")
Country.create(:iso => 'SY', :continent => Continent.find(2), "Syrian Arab Republic")
Country.create(:iso => 'TW', :continent => Continent.find(2), "Taiwan")
Country.create(:iso => 'TJ', :continent => Continent.find(2), "Tajikistan")
Country.create(:iso => 'TZ', :continent => Continent.find(1), "Tanzania")
Country.create(:iso => 'TH', :continent => Continent.find(2), "Thailand")
Country.create(:iso => 'TL', :continent => Continent.find(2), "Timor-Leste")
Country.create(:iso => 'TG', :continent => Continent.find(1), "Togo")
Country.create(:iso => 'TK', :continent => Continent.find(6), "Tokelau")
Country.create(:iso => 'TO', :continent => Continent.find(6), "Tonga")
Country.create(:iso => 'TT', :continent => Continent.find(4), "Trinidad and Tobago")
Country.create(:iso => 'TN', :continent => Continent.find(1), "Tunisia")
Country.create(:iso => 'TR', :continent => Continent.find(2), "Turkey")
Country.create(:iso => 'TM', :continent => Continent.find(2), "Turkmenistan")
Country.create(:iso => 'TC', :continent => Continent.find(4), "Turks and Caicos Islands")
Country.create(:iso => 'TV', :continent => Continent.find(6), "Tuvalu")
Country.create(:iso => 'UG', :continent => Continent.find(1), "Uganda")
Country.create(:iso => 'UA', :continent => Continent.find(3), "Ukraine")
Country.create(:iso => 'AE', :continent => Continent.find(2), "United Arab Emirates")
Country.create(:iso => 'GB', :continent => Continent.find(3), "United Kingdom of Great Britain & Northern Ireland")
Country.create(:iso => 'US', :continent => Continent.find(4), "United States of America")
Country.create(:iso => 'UM', :continent => Continent.find(6), "United States Minor Outlying Islands")
Country.create(:iso => 'VI', :continent => Continent.find(4), "United States Virgin Islands")
Country.create(:iso => 'UY', :continent => Continent.find(5), "Uruguay")
Country.create(:iso => 'UZ', :continent => Continent.find(2), "Uzbekistan")
Country.create(:iso => 'VU', :continent => Continent.find(6), "Vanuatu")
Country.create(:iso => 'VE', :continent => Continent.find(5), "Venezuela")
Country.create(:iso => 'VN', :continent => Continent.find(2), "Vietnam")
Country.create(:iso => 'WF', :continent => Continent.find(6), "Wallis and Futuna")
Country.create(:iso => 'EH', :continent => Continent.find(1), "Western Sahara")
Country.create(:iso => 'YE', :continent => Continent.find(2), "Yemen")
Country.create(:iso => 'ZM', :continent => Continent.find(1), "Zambia")
Country.create(:iso => 'ZW', :continent => Continent.find(1), "Zimbabwe")