Continent.delete_all
connection.execute("ALTER TABLE continents AUTO_INCREMENT = 1")
Continent.create(:iso => 'AF', :name => 'Africa')
Continent.create(:iso => 'AS', :name => 'Asia')
Continent.create(:iso => 'EU', :name => 'Europe')
Continent.create(:iso => 'NA', :name => 'North America')
Continent.create(:iso => 'SA', :name => 'South America')
Continent.create(:iso => 'OC', :name => 'Oceania')
Continent.create(:iso => 'AN', :name => 'Antarctica')

Country.delete_all
connection.execute("ALTER TABLE countries AUTO_INCREMENT = 1")
Country.create(:iso => 'AF', :continent => Continent.find(2), :name => "Afghanistan")
Country.create(:iso => 'AX', :continent => Continent.find(3), :name => "Åland Islands")
Country.create(:iso => 'AL', :continent => Continent.find(3), :name => "Albania")
Country.create(:iso => 'DZ', :continent => Continent.find(1), :name => "Algeria")
Country.create(:iso => 'AS', :continent => Continent.find(6), :name => "American Samoa")
Country.create(:iso => 'AD', :continent => Continent.find(3), :name => "Andorra")
Country.create(:iso => 'AO', :continent => Continent.find(1), :name => "Angola")
Country.create(:iso => 'AI', :continent => Continent.find(4), :name => "Anguilla")
Country.create(:iso => 'AQ', :continent => Continent.find(7), :name => "Antarctica")
Country.create(:iso => 'AG', :continent => Continent.find(4), :name => "Antigua and Barbuda")
Country.create(:iso => 'AR', :continent => Continent.find(5), :name => "Argentina")
Country.create(:iso => 'AM', :continent => Continent.find(2), :name => "Armenia")
Country.create(:iso => 'AW', :continent => Continent.find(4), :name => "Aruba")
Country.create(:iso => 'AU', :continent => Continent.find(6), :name => "Australia")
Country.create(:iso => 'AT', :continent => Continent.find(3), :name => "Austria")
Country.create(:iso => 'AZ', :continent => Continent.find(2), :name => "Azerbaijan")
Country.create(:iso => 'BS', :continent => Continent.find(4), :name => "Bahamas")
Country.create(:iso => 'BH', :continent => Continent.find(2), :name => "Bahrain")
Country.create(:iso => 'BD', :continent => Continent.find(2), :name => "Bangladesh")
Country.create(:iso => 'BB', :continent => Continent.find(4), :name => "Barbados")
Country.create(:iso => 'BY', :continent => Continent.find(3), :name => "Belarus")
Country.create(:iso => 'BE', :continent => Continent.find(3), :name => "Belgium")
Country.create(:iso => 'BZ', :continent => Continent.find(4), :name => "Belize")
Country.create(:iso => 'BJ', :continent => Continent.find(1), :name => "Benin")
Country.create(:iso => 'BM', :continent => Continent.find(4), :name => "Bermuda")
Country.create(:iso => 'BT', :continent => Continent.find(2), :name => "Bhutan")
Country.create(:iso => 'BO', :continent => Continent.find(5), :name => "Bolivia")
Country.create(:iso => 'BQ', :continent => Continent.find(4), :name => "Bonaire, Sint Eustatius and Saba")
Country.create(:iso => 'BA', :continent => Continent.find(3), :name => "Bosnia and Herzegovina")
Country.create(:iso => 'BW', :continent => Continent.find(1), :name => "Botswana")
Country.create(:iso => 'BV', :continent => Continent.find(7), :name => "Bouvet Island (Bouvetoya)")
Country.create(:iso => 'BR', :continent => Continent.find(5), :name => "Brazil")
Country.create(:iso => 'IO', :continent => Continent.find(2), :name => "British Indian Ocean Territory (Chagos Archipelago)")
Country.create(:iso => 'VG', :continent => Continent.find(4), :name => "British Virgin Islands")
Country.create(:iso => 'BN', :continent => Continent.find(2), :name => "Brunei Darussalam")
Country.create(:iso => 'BG', :continent => Continent.find(3), :name => "Bulgaria")
Country.create(:iso => 'BF', :continent => Continent.find(1), :name => "Burkina Faso")
Country.create(:iso => 'BI', :continent => Continent.find(1), :name => "Burundi")
Country.create(:iso => 'KH', :continent => Continent.find(2), :name => "Cambodia")
Country.create(:iso => 'CM', :continent => Continent.find(1), :name => "Cameroon")
Country.create(:iso => 'CA', :continent => Continent.find(4), :name => "Canada")
Country.create(:iso => 'CV', :continent => Continent.find(1), :name => "Cape Verde")
Country.create(:iso => 'KY', :continent => Continent.find(4), :name => "Cayman Islands")
Country.create(:iso => 'CF', :continent => Continent.find(1), :name => "Central African Republic")
Country.create(:iso => 'TD', :continent => Continent.find(1), :name => "Chad")
Country.create(:iso => 'CL', :continent => Continent.find(5), :name => "Chile")
Country.create(:iso => 'CN', :continent => Continent.find(2), :name => "China")
Country.create(:iso => 'CX', :continent => Continent.find(2), :name => "Christmas Island")
Country.create(:iso => 'CC', :continent => Continent.find(2), :name => "Cocos (Keeling) Islands")
Country.create(:iso => 'CO', :continent => Continent.find(5), :name => "Colombia")
Country.create(:iso => 'KM', :continent => Continent.find(1), :name => "Comoros")
Country.create(:iso => 'CD', :continent => Continent.find(1), :name => "Congo")
Country.create(:iso => 'CG', :continent => Continent.find(1), :name => "Congo")
Country.create(:iso => 'CK', :continent => Continent.find(6), :name => "Cook Islands")
Country.create(:iso => 'CR', :continent => Continent.find(4), :name => "Costa Rica")
Country.create(:iso => 'CI', :continent => Continent.find(1), :name => "Cote d'Ivoire")
Country.create(:iso => 'HR', :continent => Continent.find(3), :name => "Croatia")
Country.create(:iso => 'CU', :continent => Continent.find(4), :name => "Cuba")
Country.create(:iso => 'CW', :continent => Continent.find(4), :name => "Curaçao")
Country.create(:iso => 'CY', :continent => Continent.find(2), :name => "Cyprus")
Country.create(:iso => 'CZ', :continent => Continent.find(3), :name => "Czech Republic")
Country.create(:iso => 'DK', :continent => Continent.find(3), :name => "Denmark")
Country.create(:iso => 'DJ', :continent => Continent.find(1), :name => "Djibouti")
Country.create(:iso => 'DM', :continent => Continent.find(4), :name => "Dominica")
Country.create(:iso => 'DO', :continent => Continent.find(4), :name => "Dominican Republic")
Country.create(:iso => 'EC', :continent => Continent.find(5), :name => "Ecuador")
Country.create(:iso => 'EG', :continent => Continent.find(1), :name => "Egypt")
Country.create(:iso => 'SV', :continent => Continent.find(4), :name => "El Salvador")
Country.create(:iso => 'GQ', :continent => Continent.find(1), :name => "Equatorial Guinea")
Country.create(:iso => 'ER', :continent => Continent.find(1), :name => "Eritrea")
Country.create(:iso => 'EE', :continent => Continent.find(3), :name => "Estonia")
Country.create(:iso => 'ET', :continent => Continent.find(1), :name => "Ethiopia")
Country.create(:iso => 'FO', :continent => Continent.find(3), :name => "Faroe Islands")
Country.create(:iso => 'FK', :continent => Continent.find(5), :name => "Falkland Islands (Malvinas)")
Country.create(:iso => 'FJ', :continent => Continent.find(6), :name => "Fiji")
Country.create(:iso => 'FI', :continent => Continent.find(3), :name => "Finland")
Country.create(:iso => 'FR', :continent => Continent.find(3), :name => "France")
Country.create(:iso => 'GF', :continent => Continent.find(5), :name => "French Guiana")
Country.create(:iso => 'PF', :continent => Continent.find(6), :name => "French Polynesia")
Country.create(:iso => 'TF', :continent => Continent.find(7), :name => "French Southern Territories")
Country.create(:iso => 'GA', :continent => Continent.find(1), :name => "Gabon")
Country.create(:iso => 'GM', :continent => Continent.find(1), :name => "Gambia")
Country.create(:iso => 'GE', :continent => Continent.find(2), :name => "Georgia")
Country.create(:iso => 'DE', :continent => Continent.find(3), :name => "Germany")
Country.create(:iso => 'GH', :continent => Continent.find(1), :name => "Ghana")
Country.create(:iso => 'GI', :continent => Continent.find(3), :name => "Gibraltar")
Country.create(:iso => 'GR', :continent => Continent.find(3), :name => "Greece")
Country.create(:iso => 'GL', :continent => Continent.find(4), :name => "Greenland")
Country.create(:iso => 'GD', :continent => Continent.find(4), :name => "Grenada")
Country.create(:iso => 'GP', :continent => Continent.find(4), :name => "Guadeloupe")
Country.create(:iso => 'GU', :continent => Continent.find(6), :name => "Guam")
Country.create(:iso => 'GT', :continent => Continent.find(4), :name => "Guatemala")
Country.create(:iso => 'GG', :continent => Continent.find(3), :name => "Guernsey")
Country.create(:iso => 'GN', :continent => Continent.find(1), :name => "Guinea")
Country.create(:iso => 'GW', :continent => Continent.find(1), :name => "Guinea-Bissau")
Country.create(:iso => 'GY', :continent => Continent.find(5), :name => "Guyana")
Country.create(:iso => 'HT', :continent => Continent.find(4), :name => "Haiti")
Country.create(:iso => 'HM', :continent => Continent.find(7), :name => "Heard Island and McDonald Islands")
Country.create(:iso => 'VA', :continent => Continent.find(3), :name => "Holy See (Vatican City State)")
Country.create(:iso => 'HN', :continent => Continent.find(4), :name => "Honduras")
Country.create(:iso => 'HK', :continent => Continent.find(2), :name => "Hong Kong")
Country.create(:iso => 'HU', :continent => Continent.find(3), :name => "Hungary")
Country.create(:iso => 'IS', :continent => Continent.find(3), :name => "Iceland")
Country.create(:iso => 'IN', :continent => Continent.find(2), :name => "India")
Country.create(:iso => 'ID', :continent => Continent.find(2), :name => "Indonesia")
Country.create(:iso => 'IR', :continent => Continent.find(2), :name => "Iran")
Country.create(:iso => 'IQ', :continent => Continent.find(2), :name => "Iraq")
Country.create(:iso => 'IE', :continent => Continent.find(3), :name => "Ireland")
Country.create(:iso => 'IM', :continent => Continent.find(3), :name => "Isle of Man")
Country.create(:iso => 'IL', :continent => Continent.find(2), :name => "Israel")
Country.create(:iso => 'IT', :continent => Continent.find(3), :name => "Italy")
Country.create(:iso => 'JM', :continent => Continent.find(4), :name => "Jamaica")
Country.create(:iso => 'JP', :continent => Continent.find(2), :name => "Japan")
Country.create(:iso => 'JE', :continent => Continent.find(3), :name => "Jersey")
Country.create(:iso => 'JO', :continent => Continent.find(2), :name => "Jordan")
Country.create(:iso => 'KZ', :continent => Continent.find(2), :name => "Kazakhstan")
Country.create(:iso => 'KE', :continent => Continent.find(1), :name => "Kenya")
Country.create(:iso => 'KI', :continent => Continent.find(6), :name => "Kiribati")
Country.create(:iso => 'KP', :continent => Continent.find(2), :name => "Democratic People's Republic of Korea")
Country.create(:iso => 'KR', :continent => Continent.find(2), :name => "Republic of Korea")
Country.create(:iso => 'KW', :continent => Continent.find(2), :name => "Kuwait")
Country.create(:iso => 'KG', :continent => Continent.find(2), :name => "Kyrgyz Republic")
Country.create(:iso => 'LA', :continent => Continent.find(2), :name => "Lao People's Democratic Republic")
Country.create(:iso => 'LV', :continent => Continent.find(3), :name => "Latvia")
Country.create(:iso => 'LB', :continent => Continent.find(2), :name => "Lebanon")
Country.create(:iso => 'LS', :continent => Continent.find(1), :name => "Lesotho")
Country.create(:iso => 'LR', :continent => Continent.find(1), :name => "Liberia")
Country.create(:iso => 'LY', :continent => Continent.find(1), :name => "Libya")
Country.create(:iso => 'LI', :continent => Continent.find(3), :name => "Liechtenstein")
Country.create(:iso => 'LT', :continent => Continent.find(3), :name => "Lithuania")
Country.create(:iso => 'LU', :continent => Continent.find(3), :name => "Luxembourg")
Country.create(:iso => 'MO', :continent => Continent.find(2), :name => "Macao")
Country.create(:iso => 'MK', :continent => Continent.find(3), :name => "Macedonia")
Country.create(:iso => 'MG', :continent => Continent.find(1), :name => "Madagascar")
Country.create(:iso => 'MW', :continent => Continent.find(1), :name => "Malawi")
Country.create(:iso => 'MY', :continent => Continent.find(2), :name => "Malaysia")
Country.create(:iso => 'MV', :continent => Continent.find(2), :name => "Maldives")
Country.create(:iso => 'ML', :continent => Continent.find(1), :name => "Mali")
Country.create(:iso => 'MT', :continent => Continent.find(3), :name => "Malta")
Country.create(:iso => 'MH', :continent => Continent.find(6), :name => "Marshall Islands")
Country.create(:iso => 'MQ', :continent => Continent.find(4), :name => "Martinique")
Country.create(:iso => 'MR', :continent => Continent.find(1), :name => "Mauritania")
Country.create(:iso => 'MU', :continent => Continent.find(1), :name => "Mauritius")
Country.create(:iso => 'YT', :continent => Continent.find(1), :name => "Mayotte")
Country.create(:iso => 'MX', :continent => Continent.find(4), :name => "Mexico")
Country.create(:iso => 'FM', :continent => Continent.find(6), :name => "Micronesia")
Country.create(:iso => 'MD', :continent => Continent.find(3), :name => "Moldova")
Country.create(:iso => 'MC', :continent => Continent.find(3), :name => "Monaco")
Country.create(:iso => 'MN', :continent => Continent.find(2), :name => "Mongolia")
Country.create(:iso => 'ME', :continent => Continent.find(3), :name => "Montenegro")
Country.create(:iso => 'MS', :continent => Continent.find(4), :name => "Montserrat")
Country.create(:iso => 'MA', :continent => Continent.find(1), :name => "Morocco")
Country.create(:iso => 'MZ', :continent => Continent.find(1), :name => "Mozambique")
Country.create(:iso => 'MM', :continent => Continent.find(2), :name => "Myanmar")
Country.create(:iso => 'NA', :continent => Continent.find(1), :name => "Namibia")
Country.create(:iso => 'NR', :continent => Continent.find(6), :name => "Nauru")
Country.create(:iso => 'NP', :continent => Continent.find(2), :name => "Nepal")
Country.create(:iso => 'NL', :continent => Continent.find(3), :name => "Netherlands")
Country.create(:iso => 'NC', :continent => Continent.find(6), :name => "New Caledonia")
Country.create(:iso => 'NZ', :continent => Continent.find(6), :name => "New Zealand")
Country.create(:iso => 'NI', :continent => Continent.find(4), :name => "Nicaragua")
Country.create(:iso => 'NE', :continent => Continent.find(1), :name => "Niger")
Country.create(:iso => 'NG', :continent => Continent.find(1), :name => "Nigeria")
Country.create(:iso => 'NU', :continent => Continent.find(6), :name => "Niue")
Country.create(:iso => 'NF', :continent => Continent.find(6), :name => "Norfolk Island")
Country.create(:iso => 'MP', :continent => Continent.find(6), :name => "Northern Mariana Islands")
Country.create(:iso => 'NO', :continent => Continent.find(3), :name => "Norway")
Country.create(:iso => 'OM', :continent => Continent.find(2), :name => "Oman")
Country.create(:iso => 'PK', :continent => Continent.find(2), :name => "Pakistan")
Country.create(:iso => 'PW', :continent => Continent.find(6), :name => "Palau")
Country.create(:iso => 'PS', :continent => Continent.find(2), :name => "Palestinian Territory")
Country.create(:iso => 'PA', :continent => Continent.find(4), :name => "Panama")
Country.create(:iso => 'PG', :continent => Continent.find(6), :name => "Papua New Guinea")
Country.create(:iso => 'PY', :continent => Continent.find(5), :name => "Paraguay")
Country.create(:iso => 'PE', :continent => Continent.find(5), :name => "Peru")
Country.create(:iso => 'PH', :continent => Continent.find(2), :name => "Philippines")
Country.create(:iso => 'PN', :continent => Continent.find(6), :name => "Pitcairn Islands")
Country.create(:iso => 'PL', :continent => Continent.find(3), :name => "Poland")
Country.create(:iso => 'PT', :continent => Continent.find(3), :name => "Portugal")
Country.create(:iso => 'PR', :continent => Continent.find(4), :name => "Puerto Rico")
Country.create(:iso => 'QA', :continent => Continent.find(2), :name => "Qatar")
Country.create(:iso => 'RE', :continent => Continent.find(1), :name => "Réunion")
Country.create(:iso => 'RO', :continent => Continent.find(3), :name => "Romania")
Country.create(:iso => 'RU', :continent => Continent.find(3), :name => "Russian Federation")
Country.create(:iso => 'RW', :continent => Continent.find(1), :name => "Rwanda")
Country.create(:iso => 'BL', :continent => Continent.find(4), :name => "Saint Barthélemy")
Country.create(:iso => 'SH', :continent => Continent.find(1), :name => "Saint Helena, Ascension and Tristan da Cunha")
Country.create(:iso => 'KN', :continent => Continent.find(4), :name => "Saint Kitts and Nevis")
Country.create(:iso => 'LC', :continent => Continent.find(4), :name => "Saint Lucia")
Country.create(:iso => 'MF', :continent => Continent.find(4), :name => "Saint Martin")
Country.create(:iso => 'PM', :continent => Continent.find(4), :name => "Saint Pierre and Miquelon")
Country.create(:iso => 'VC', :continent => Continent.find(4), :name => "Saint Vincent and the Grenadines")
Country.create(:iso => 'WS', :continent => Continent.find(6), :name => "Samoa")
Country.create(:iso => 'SM', :continent => Continent.find(3), :name => "San Marino")
Country.create(:iso => 'ST', :continent => Continent.find(1), :name => "Sao Tome and Principe")
Country.create(:iso => 'SA', :continent => Continent.find(2), :name => "Saudi Arabia")
Country.create(:iso => 'SN', :continent => Continent.find(1), :name => "Senegal")
Country.create(:iso => 'RS', :continent => Continent.find(3), :name => "Serbia")
Country.create(:iso => 'SC', :continent => Continent.find(1), :name => "Seychelles")
Country.create(:iso => 'SL', :continent => Continent.find(1), :name => "Sierra Leone")
Country.create(:iso => 'SG', :continent => Continent.find(2), :name => "Singapore")
Country.create(:iso => 'SX', :continent => Continent.find(4), :name => "Sint Maarten (Dutch part)")
Country.create(:iso => 'SK', :continent => Continent.find(3), :name => "Slovakia (Slovak Republic)")
Country.create(:iso => 'SI', :continent => Continent.find(3), :name => "Slovenia")
Country.create(:iso => 'SB', :continent => Continent.find(6), :name => "Solomon Islands")
Country.create(:iso => 'SO', :continent => Continent.find(1), :name => "Somalia")
Country.create(:iso => 'ZA', :continent => Continent.find(1), :name => "South Africa")
Country.create(:iso => 'GS', :continent => Continent.find(7), :name => "South Georgia and the South Sandwich Islands")
Country.create(:iso => 'SS', :continent => Continent.find(1), :name => "South Sudan")
Country.create(:iso => 'ES', :continent => Continent.find(3), :name => "Spain")
Country.create(:iso => 'LK', :continent => Continent.find(2), :name => "Sri Lanka")
Country.create(:iso => 'SD', :continent => Continent.find(1), :name => "Sudan")
Country.create(:iso => 'SR', :continent => Continent.find(5), :name => "Suriname")
Country.create(:iso => 'SJ', :continent => Continent.find(3), :name => "Svalbard & Jan Mayen Islands")
Country.create(:iso => 'SZ', :continent => Continent.find(1), :name => "Swaziland")
Country.create(:iso => 'SE', :continent => Continent.find(3), :name => "Sweden")
Country.create(:iso => 'CH', :continent => Continent.find(3), :name => "Switzerland")
Country.create(:iso => 'SY', :continent => Continent.find(2), :name => "Syrian Arab Republic")
Country.create(:iso => 'TW', :continent => Continent.find(2), :name => "Taiwan")
Country.create(:iso => 'TJ', :continent => Continent.find(2), :name => "Tajikistan")
Country.create(:iso => 'TZ', :continent => Continent.find(1), :name => "Tanzania")
Country.create(:iso => 'TH', :continent => Continent.find(2), :name => "Thailand")
Country.create(:iso => 'TL', :continent => Continent.find(2), :name => "Timor-Leste")
Country.create(:iso => 'TG', :continent => Continent.find(1), :name => "Togo")
Country.create(:iso => 'TK', :continent => Continent.find(6), :name => "Tokelau")
Country.create(:iso => 'TO', :continent => Continent.find(6), :name => "Tonga")
Country.create(:iso => 'TT', :continent => Continent.find(4), :name => "Trinidad and Tobago")
Country.create(:iso => 'TN', :continent => Continent.find(1), :name => "Tunisia")
Country.create(:iso => 'TR', :continent => Continent.find(2), :name => "Turkey")
Country.create(:iso => 'TM', :continent => Continent.find(2), :name => "Turkmenistan")
Country.create(:iso => 'TC', :continent => Continent.find(4), :name => "Turks and Caicos Islands")
Country.create(:iso => 'TV', :continent => Continent.find(6), :name => "Tuvalu")
Country.create(:iso => 'UG', :continent => Continent.find(1), :name => "Uganda")
Country.create(:iso => 'UA', :continent => Continent.find(3), :name => "Ukraine")
Country.create(:iso => 'AE', :continent => Continent.find(2), :name => "United Arab Emirates")
Country.create(:iso => 'GB', :continent => Continent.find(3), :name => "United Kingdom of Great Britain & Northern Ireland")
Country.create(:iso => 'US', :continent => Continent.find(4), :name => "United States of America")
Country.create(:iso => 'UM', :continent => Continent.find(6), :name => "United States Minor Outlying Islands")
Country.create(:iso => 'VI', :continent => Continent.find(4), :name => "United States Virgin Islands")
Country.create(:iso => 'UY', :continent => Continent.find(5), :name => "Uruguay")
Country.create(:iso => 'UZ', :continent => Continent.find(2), :name => "Uzbekistan")
Country.create(:iso => 'VU', :continent => Continent.find(6), :name => "Vanuatu")
Country.create(:iso => 'VE', :continent => Continent.find(5), :name => "Venezuela")
Country.create(:iso => 'VN', :continent => Continent.find(2), :name => "Vietnam")
Country.create(:iso => 'WF', :continent => Continent.find(6), :name => "Wallis and Futuna")
Country.create(:iso => 'EH', :continent => Continent.find(1), :name => "Western Sahara")
Country.create(:iso => 'YE', :continent => Continent.find(2), :name => "Yemen")
Country.create(:iso => 'ZM', :continent => Continent.find(1), :name => "Zambia")
Country.create(:iso => 'ZW', :continent => Continent.find(1), :name => "Zimbabwe")